### ISSUE TITLE
Cannot upgrade Redis to 5.0.1

### ISSUE THREAD

**Issue by maciejpankanin** [brpoplpush/brpoplpush-redis_script#23]
Recently I updated my bundle which resulted in updating `redis` to "5.0.0". As you may know this version does not work with Sidekiq < 7. There is a fix for it in `redis` 5.0.1 but this is against dependencies constraints for this gem. Is there a purpose for it or it can be easily updated? :)

**Comment by vladimirtemnikov** [comment]
Same problem, blocks updating :(
Can this be resolved by bump of max Redis gem version?

**Comment by gstokkink** [comment]
This has been fixed in https://github.com/brpoplpush/brpoplpush-redis_script/commit/96c3f2617668b5c971772ffe2ad681c188cb11fa.

**Comment by mhenrixon** [comment]
https://github.com/mhenrixon/sidekiq-unique-jobs/releases/tag/v8.0.6
