### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mhenrixon** [brpoplpush/brpoplpush-redis_script#4]
We should update the README.md with some usage information. It would also be great to add some badges to the readme from https://travis-ci.com (build status), https://codeclimate.com (test coverage + quality)

**Comment by mberlanda** [comment]
Would #15 be enough to complete this task or are you planning to add other badges? :smile:

**Comment by mhenrixon** [comment]
The README.md could benefit from some improvement or we could remove some of the code :)
